### ISSUE TITLE
 I am much obliged.

### ISSUE THREAD

**Issue by ranaijaz232** [GabauerDavid/ConnectednessApproach#2]
Thank you Professor, You have done a great job and I appreciate you.

**Comment by GabauerDavid** [comment]
Hi Ranaijaz,

Besides your disrespectful request and the fact that I have not received a single mail of yours - there is not even one in my spam folder - this is not the right site to discuss issues you have with the online estimation platform. I have another GitHub repository dedicated to replicate results of various papers where you will find a lot of example xlsx files that are suitable for the online estimation platform. 

This website describes how the package can be installed:
https://github.com/GabauerDavid/ConnectednessApproach
and here you can find a lot of examples as well:
https://gabauerdavid.github.io/ConnectednessApproach/#Dynamic_Connectedness_Measures

Both the ConnectednessApproach as well as the Online Estimation Platforms are services I offer for free. There is no institution or university which finances this project which is why the free shinyapps version - that sometimes disconnects from the server if large datasets are uploaded - is used. All those information could have been found easily when you would have googled it which you haven’t done - obviously. 

To sum it up. None of your mails reached me (even though I have three accounts which are all visible publicly), you have posted inappropriately a comment on the ConnectednessApproach website - which has nothing to do with the online estimation platform - about the fact whether I could share the code with you - even though you find exactly the requested code on this particular website. And all of this has been done in the most rude, accusing and disrespectful way anyone has ever contacted me. I really don’t know why you think that addressing this issue in such a rude and disrespectful way is appropriate in any imaginable scenario but I would kindly advice you that the next time you are dissatisfied or disappointed with something cool down and try to be respectful.

To put it frankly, it is my code, which I have created myself over several years as well as the online estimation platform and the R package which took me thousands of hours - that I could have spent differently otherwise - and I never had to share it with anyone else. So the only reason why you can use this code is because of the fact that I wanted to help others. Disrespectful people like you are the only reason why I haven’t published the code earlier as I never wanted to deal with such guys or accusations. The best thing to avoid such discussions would be to immediately delete all online estimation platforms and discontinue the work on the ConnectednessApproach however there are luckily far more people who value these service who give me the strength dealing with ignorant and disrespectful people like you. As I am currently on my deserved vacation I would like to thank you for fucking up my day. I hope this was your intention and you are happy with your result. 
Just in general, comments like this will be deleted or left unanswered in the future as there is no point in wasting time on them.
